ARG ELIXIR_VERSION
ARG OTP_VERSION
ARG ARCH
ARG GCC_VERSION
ARG LIBC
ARG MIX_ENV
ARG GITHUB_API_TOKEN

FROM hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-ubuntu-jammy

ARG ELIXIR_VERSION
ARG OTP_VERSION
ARG ARCH
ARG GCC_VERSION
ARG LIBC
ARG MIX_ENV
ARG GITHUB_API_TOKEN

# install build dependencies
RUN apt-get update && apt-get install -y bash build-essential git curl jq xz-utils

# Nerves toolchains for cross compilation
RUN git clone https://github.com/lawik/asdf-plugin-nerves-toolchain.git /apnt
WORKDIR /apnt
RUN mkdir /apnt/download
RUN export ASDF_INSTALL_TYPE="version" && \
    export ASDF_INSTALL_VERSION="${GCC_VERSION}-${ARCH}-nerves-linux-${LIBC}" && \
    export ASDF_INSTALL_PATH="/apnt/toolchain/" && \
    export ASDF_DOWNLOAD_PATH="/apnt/download" && \
    ./bin/download

# Set up cross-compilation environment
# Docker ENV doesn't cascade references within a single block,
# so we use a shell script to set up the toolchain paths.
RUN TC_BASE="/apnt/download" && \
    GCC_PREFIX="${ARCH}-nerves-linux-${LIBC}-" && \
    echo "export PATH=\"\$PATH:${TC_BASE}/bin\"" >> /etc/profile.d/toolchain.sh && \
    echo "export CC=\"${GCC_PREFIX}gcc\"" >> /etc/profile.d/toolchain.sh && \
    echo "export CXX=\"${GCC_PREFIX}g++\"" >> /etc/profile.d/toolchain.sh && \
    echo "export LD=\"${GCC_PREFIX}ld\"" >> /etc/profile.d/toolchain.sh && \
    echo "export AR=\"${GCC_PREFIX}ar\"" >> /etc/profile.d/toolchain.sh && \
    echo "export AS=\"${GCC_PREFIX}as\"" >> /etc/profile.d/toolchain.sh && \
    echo "export NM=\"${GCC_PREFIX}nm\"" >> /etc/profile.d/toolchain.sh && \
    echo "export RANLIB=\"${GCC_PREFIX}ranlib\"" >> /etc/profile.d/toolchain.sh && \
    echo "export OBJCOPY=\"${GCC_PREFIX}objcopy\"" >> /etc/profile.d/toolchain.sh && \
    echo "export STRIP=\"${GCC_PREFIX}strip\"" >> /etc/profile.d/toolchain.sh && \
    echo "export LDFLAGS=\"-L${TC_BASE}/lib\"" >> /etc/profile.d/toolchain.sh && \
    echo "export CFLAGS=\"-I${TC_BASE}/include\"" >> /etc/profile.d/toolchain.sh && \
    echo "export CPPFLAGS=\"-I${TC_BASE}/include\"" >> /etc/profile.d/toolchain.sh && \
    echo "export CROSSCOMPILE=\"${GCC_PREFIX}\"" >> /etc/profile.d/toolchain.sh

ENV PATH="$PATH:/apnt/download/bin"

COPY . /build
WORKDIR /build

# install hex + rebar
RUN mix local.hex --force && \
    mix local.rebar --force

# set build ENV
ENV MIX_ENV=${MIX_ENV}

# install mix dependencies and compile
RUN mix do deps.get, compile
