ARG ELIXIR_VERSION
ARG OTP_VERSION
ARG BASE_IMAGE_OS="debian-bookworm-20260223"
ARG ARCH
ARG GCC_VERSION
ARG ABI
ARG MIX_ENV
ARG GITHUB_API_TOKEN

FROM hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-${BASE_IMAGE_OS}

ARG ARCH
ARG GCC_VERSION
ARG ABI
ARG MIX_ENV
ARG GITHUB_API_TOKEN

# install build dependencies
RUN apt-get update && apt-get install -y bash build-essential git curl jq xz-utils

# Nerves toolchains for cross compilation
RUN git clone https://github.com/lawik/asdf-plugin-nerves-toolchain.git /apnt
WORKDIR /apnt
RUN mkdir /apnt/download
RUN export ASDF_INSTALL_TYPE="version" && \
    export ASDF_INSTALL_VERSION="${GCC_VERSION}-${ARCH}-nerves-linux-${ABI}" && \
    export ASDF_INSTALL_PATH="/apnt/toolchain/" && \
    export ASDF_DOWNLOAD_PATH="/apnt/download" && \
    ./bin/download

# Set up cross-compilation environment via Docker ENV
ENV PATH="$PATH:/apnt/download/bin" \
    CC="${ARCH}-nerves-linux-${ABI}-gcc" \
    CXX="${ARCH}-nerves-linux-${ABI}-g++" \
    LD="${ARCH}-nerves-linux-${ABI}-ld" \
    AR="${ARCH}-nerves-linux-${ABI}-ar" \
    AS="${ARCH}-nerves-linux-${ABI}-as" \
    NM="${ARCH}-nerves-linux-${ABI}-nm" \
    RANLIB="${ARCH}-nerves-linux-${ABI}-ranlib" \
    OBJCOPY="${ARCH}-nerves-linux-${ABI}-objcopy" \
    STRIP="${ARCH}-nerves-linux-${ABI}-strip" \
    CROSSCOMPILE="${ARCH}-nerves-linux-${ABI}-" \
    LDFLAGS="-L/apnt/download/lib" \
    CFLAGS="-I/apnt/download/include" \
    CPPFLAGS="-I/apnt/download/include"

COPY . /build
WORKDIR /build

# install hex + rebar
RUN mix local.hex --force && \
    mix local.rebar --force

# set build ENV
ENV MIX_ENV=${MIX_ENV}

# compile with rebar3
RUN msg=$(mix local.rebar --force) && \
    rebar_path=${msg#"* creating "} && \
    "$rebar_path" compile
