ARG ELIXIR_VERSION
ARG OTP_VERSION
ARG BASE_IMAGE_OS="debian-bookworm-20260223"
ARG ARCH
ARG GCC_VERSION
ARG LIBC
ARG MIX_ENV
ARG GITHUB_API_TOKEN

FROM hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-${BASE_IMAGE_OS}

ARG ARCH
ARG GCC_VERSION
ARG LIBC
ARG MIX_ENV
ARG GITHUB_API_TOKEN

# install build dependencies
RUN apt-get update && apt-get install -y bash build-essential git curl jq xz-utils

# Nerves toolchains for cross compilation
RUN git clone https://github.com/lawik/asdf-plugin-nerves-toolchain.git /apnt
WORKDIR /apnt
RUN mkdir /apnt/download
RUN export ASDF_INSTALL_TYPE="version" && \
    export ASDF_INSTALL_VERSION="${GCC_VERSION}-${ARCH}-nerves-linux-${LIBC}" && \
    export ASDF_INSTALL_PATH="/apnt/toolchain/" && \
    export ASDF_DOWNLOAD_PATH="/apnt/download" && \
    ./bin/download

# Set up cross-compilation environment
RUN TC_BASE="/apnt/download" && \
    GCC_PREFIX="${ARCH}-nerves-linux-${LIBC}-" && \
    echo "export PATH=\"\$PATH:${TC_BASE}/bin\"" >> /etc/profile.d/toolchain.sh && \
    echo "export CC=\"${GCC_PREFIX}gcc\"" >> /etc/profile.d/toolchain.sh && \
    echo "export CXX=\"${GCC_PREFIX}g++\"" >> /etc/profile.d/toolchain.sh && \
    echo "export LD=\"${GCC_PREFIX}ld\"" >> /etc/profile.d/toolchain.sh && \
    echo "export AR=\"${GCC_PREFIX}ar\"" >> /etc/profile.d/toolchain.sh && \
    echo "export CROSSCOMPILE=\"${GCC_PREFIX}\"" >> /etc/profile.d/toolchain.sh

ENV PATH="$PATH:/apnt/download/bin"

COPY . /build
WORKDIR /build

# install hex + rebar
RUN mix local.hex --force && \
    mix local.rebar --force

# set build ENV
ENV MIX_ENV=${MIX_ENV}

# compile with rebar3
RUN msg=$(mix local.rebar --force) && \
    rebar_path=${msg#"* creating "} && \
    "$rebar_path" compile
